-- Fix ecologic_products table schema recognition
-- This migration ensures the table is properly recognized by PostgREST

-- Drop and recreate the table to force schema cache refresh
DROP TABLE IF EXISTS public.ecologic_products_temp;

-- Create a temporary table with the same structure
CREATE TABLE public.ecologic_products_temp AS 
SELECT * FROM public.ecologic_products;

-- Drop the original table
DROP TABLE public.ecologic_products;

-- Recreate the table with explicit structure
CREATE TABLE public.ecologic_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo text NOT NULL,
    codigo text NOT NULL,
    titulo text,
    descricao text,
    img_0 text,
    img_1 text,
    img_2 text,
    categoria text,
    cor_web_principal text,
    altura numeric,
    largura numeric,
    comprimento numeric,
    peso numeric,
    variacoes jsonb
);

-- Insert data back from temporary table
INSERT INTO public.ecologic_products 
SELECT * FROM public.ecologic_products_temp;

-- Drop temporary table
DROP TABLE public.ecologic_products_temp;

-- Grant permissions
GRANT SELECT ON public.ecologic_products TO anon;
GRANT ALL PRIVILEGES ON public.ecologic_products TO authenticated;

-- Update table statistics
ANALYZE public.ecologic_products;

-- Add comment to force cache refresh
COMMENT ON TABLE public.ecologic_products IS 'Ecological products table - schema fixed and cache refreshed';