-- Force complete PostgREST schema reload

-- Drop and recreate the table to force schema refresh
DROP TABLE IF EXISTS public.ecologic_products CASCADE;

-- Recreate the table with the same structure
CREATE TABLE public.ecologic_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo TEXT NOT NULL,
    codigo TEXT NOT NULL,
    titulo TEXT,
    descricao TEXT,
    img_0 TEXT,
    img_1 TEXT,
    img_2 TEXT,
    categoria TEXT,
    cor_web_principal TEXT,
    altura NUMERIC,
    largura NUMERIC,
    comprimento NUMERIC,
    peso NUMERIC,
    variacoes JSONB
);

-- Add comment
COMMENT ON TABLE public.ecologic_products IS 'Ecological products table - Populated with data from multiple sources';

-- Enable RLS
ALTER TABLE public.ecologic_products ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT SELECT ON public.ecologic_products TO anon;
GRANT ALL PRIVILEGES ON public.ecologic_products TO authenticated;

-- Create policies
CREATE POLICY "Allow public read access" ON public.ecologic_products
    FOR SELECT USING (true);

CREATE POLICY "Allow authenticated users full access" ON public.ecologic_products
    FOR ALL USING (true);

-- Re-populate with data from the source tables
-- XBZ Products
INSERT INTO public.ecologic_products (tipo, codigo, titulo, descricao, img_0, categoria, cor_web_principal, altura, largura, comprimento, peso, variacoes)
SELECT 
    'xbz' as tipo,
    codigo,
    nome as titulo,
    descricao,
    image_link as img_0,
    categoria,
    cor_web_principal,
    altura,
    largura,
    comprimento,
    peso,
    variacoes
FROM public.xbz_products
WHERE codigo IS NOT NULL;

-- ASIA Products
INSERT INTO public.ecologic_products (tipo, codigo, titulo, descricao, img_0, categoria, cor_web_principal, altura, largura, comprimento, peso, variacoes)
SELECT 
    'asia' as tipo,
    codigo,
    nome as titulo,
    descricao,
    imagem as img_0,
    categoria,
    cor_web_principal,
    altura,
    largura,
    comprimento,
    peso,
    variacoes
FROM public.asia_products
WHERE codigo IS NOT NULL;

-- SPOT Products
INSERT INTO public.ecologic_products (tipo, codigo, titulo, descricao, img_0, categoria, cor_web_principal, altura, largura, comprimento, peso, variacoes)
SELECT 
    'spot' as tipo,
    codigo,
    nome as titulo,
    descricao,
    imagem as img_0,
    categoria,
    cor_web_principal,
    altura,
    largura,
    comprimento,
    peso,
    variacoes
FROM public.spot_products
WHERE codigo IS NOT NULL;

-- Force PostgREST to reload schema
NOTIFY pgrst, 'reload schema';

-- Verify the table exists and has data
SELECT 'Table created successfully' as status, COUNT(*) as total_records FROM public.ecologic_products;